services:
  - mongodb
language: dart
before_install:
  - mkdir -p $TRAVIS_HOME/.pub-cache
  - echo $PUB_CREDENTIALS > $TRAVIS_HOME/.pub-cache/credentials.json
  - cd unpub

cache:
  directories:
    - $TRAVIS_HOME/.pub-cache
