name: unpub
description: Private Dart Pub for Enterprise.
version: 0.1.1
homepage: https://github.com/bytedance/unpub
author: Rongjian Zhang <pd4d10@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  args: ^1.5.1
  shelf: ^0.7.5
  http: ^0.12.0
  pub_server: #^0.1.5
    git:
      url: git://github.com/pd4d10/pub_server.git
      ref: request-param
  archive: ^2.0.8
  logging: ^0.11.3
  meta: ^1.1.7
  googleapis: ^0.53.0
  yaml: ^2.1.15
  pub_semver: ^1.4.2
  json_annotation: ^2.1.0
  mongo_dart: ^0.3.4

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.6.1
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

executables:
  unpub: unpub
